### ISSUE TITLE
Exception while trying to set model

### ISSUE THREAD

**Issue by alessandromrc** [ahaggard2013/binaryninja-ollama#2]
Hi,

I just downloaded your plugin since it seems really interesting but whenever I try to set the model it always shows the UI about the Host and Port even if it is correctly configured (I can reach the API just fine with curl/my browser).

This is the stack trace I am getting:

```
[Default] Traceback (most recent call last):
[Default]   File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/plugin.py", line 127, in _default_action
[Default]     action(view_obj)
[Default]   File "/Users/alessandro/Library/Application Support/Binary Ninja/repositories/community/plugins/ahaggard2013_binaryninjaollama/plugin.py", line 40, in set_model_dialog
[Default]     model_dialog = OllamaModelDialog(client.get_model(), client.get_available_models())
[Default]   File "/Users/alessandro/Library/Application Support/Binary Ninja/repositories/community/plugins/ahaggard2013_binaryninjaollama/ollama_client.py", line 121, in get_available_models
[Default]     return [model['name'] for model in self.client.list()['models']]
[Default]   File "/Users/alessandro/Library/Application Support/Binary Ninja/repositories/community/plugins/ahaggard2013_binaryninjaollama/ollama_client.py", line 121, in <listcomp>
[Default]     return [model['name'] for model in self.client.list()['models']]
[Default]   File "/Users/alessandro/Library/Application Support/Binary Ninja/python310/site-packages/ollama/_types.py", line 32, in __getitem__
[Default]     raise KeyError(key)
[Default] KeyError: 'name'
```

My system is running on macOS so maybe you haven't tested it on this platform?

If you need to know anything more, please let me know.

**Comment by kill-your-soul** [comment]
Have same issue on Windows

**Comment by alessandromrc** [comment]
I have found the reason... it's simply that the Ollama library has changed and the client code must be changed to retrieve the models from the api... I will make a PR.

**Comment by alessandromrc** [comment]
> Have same issue on Windows

Use my fork for now I guess #3

**Comment by ahaggard2013** [comment]
Thanks for fixing this, just merged!

**Comment by alessandromrc** [comment]
No worries, you're welcome... Also nice plugin ;)

**Comment by tech4agr** [comment]
same here with mac os.
i think it should be reopen here.

[Default] Traceback (most recent call last):
[Default]   File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/plugin.py", line 127, in _default_action
[Default]     action(view_obj)
[Default]   File "/Users/neiva/Library/Application Support/Binary Ninja/repositories/community/plugins/ahaggard2013_binaryninjaollama/plugin.py", line 40, in set_model_dialog
[Default]     model_dialog = OllamaModelDialog(client.get_model(), client.get_available_models())
[Default]   File "/Users/neiva/Library/Application Support/Binary Ninja/repositories/community/plugins/ahaggard2013_binaryninjaollama/ollama_client.py", line 121, in get_available_models
[Default]     return [model['name'] for model in self.client.list()['models']]
[Default]   File "/Users/neiva/Library/Application Support/Binary Ninja/repositories/community/plugins/ahaggard2013_binaryninjaollama/ollama_client.py", line 121, in <listcomp>
[Default]     return [model['name'] for model in self.client.list()['models']]
[Default]   File "/Users/neiva/Library/Application Support/Binary Ninja/python310/site-packages/ollama/_types.py", line 32, in __getitem__
[Default]     raise KeyError(key)
[Default] KeyError: 'name'

**Comment by alessandromrc** [comment]
> same here with mac os. i think it should be reopen here.
> 
> [Default] Traceback (most recent call last): [Default] File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/plugin.py", line 127, in _default_action [Default] action(view_obj) [Default] File "/Users/neiva/Library/Application Support/Binary Ninja/repositories/community/plugins/ahaggard2013_binaryninjaollama/plugin.py", line 40, in set_model_dialog [Default] model_dialog = OllamaModelDialog(client.get_model(), client.get_available_models()) [Default] File "/Users/neiva/Library/Application Support/Binary Ninja/repositories/community/plugins/ahaggard2013_binaryninjaollama/ollama_client.py", line 121, in get_available_models [Default] return [model['name'] for model in self.client.list()['models']] [Default] File "/Users/neiva/Library/Application Support/Binary Ninja/repositories/community/plugins/ahaggard2013_binaryninjaollama/ollama_client.py", line 121, in [Default] return [model['name'] for model in self.client.list()['models']] [Default] File "/Users/neiva/Library/Application Support/Binary Ninja/python310/site-packages/ollama/_types.py", line 32, in **getitem** [Default] raise KeyError(key) [Default] KeyError: 'name'

Are you sure to be actually using the latest version of the plugin?

(Seems like that the version on the Binary Ninja store is still outdated, got the same error)

Ps. you can always perform the manual steps to update the client:

> [!WARNING]  
> Update your username

```bash
cd "/Users/alessandro/Library/Application Support/Binary Ninja/repositories/community/plugins/ahaggard2013_binaryninjaollama/"
```

then with nano / vim just update the file content with the [following](https://github.com/alessandromrc/binaryninja-ollama/blob/199d77bba446830f6b529eb2a3e4b0b7fd2df5d2/ollama_client.py).

**Comment by alessandromrc** [comment]
@ahaggard2013, I guess you should release a new version with the fixes that have been merged, otherwise users will still download the previous non-functional version and continue to come here / open new issues.

**Comment by tech4agr** [comment]
done, thanks guys
